# Generated by Django 2.0.4 on 2018-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdrf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoty',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived'), ('hidden', 'Hidden')], default='published', max_length=9),
        ),
    ]
