# Generated by Django 2.0.5 on 2018-05-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdrf', '0002_auto_20180502_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner_photo',
            new_name='banner_photos',
        ),
    ]
