# Generated by Django 2.0.5 on 2018-05-07 03:42

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogdrf', '0004_auto_20180507_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_photo',
            field=versatileimagefield.fields.VersatileImageField(upload_to=''),
        ),
    ]
